version: '3'

services:
  # Frontend service (React + Vite)
  frontend:
    build:
      context: ./blog-frontend
    ports:
      - "3000:80"  # Expose port 3000 on the host, mapped to port 80 in the container (Nginx)
    depends_on:
      - backend
    networks:
      - app-network

  # Backend service (Node.js + Express)
  backend:
    build:
      context: ./blog-backend
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: localhost
      MYSQL_USER: root
      MYSQL_PASSWORD: root@123
      MYSQL_DATABASE: blog_db
    depends_on:
      - db
    networks:
      - app-network

  # MySQL Database service
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root@123
      MYSQL_DATABASE: blog_db
    volumes:
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql  # Initialize DB with data
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
